version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: spiritual-postgres

    environment:
      POSTGRES_DB: spiritual_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890

    ports:
      - "5432:5432"

  backend:
    build: .

    ports:
      - "8080:8080"

    depends_on:
      - postgres